// react-ts/src/modules/home/Home.tsx
import { useEffect } from "react"
import { useUser } from "../../hooks/useUser";
import ModalSignIn from "../../shared/ModalSignIn";
import { useState } from "react";
import { useContacts } from "../../hooks/useContact";
import ModalDeleteContact from "./parts/ModalDeleteContact";
import ModalAddContact from "./parts/ModalAddContact";
import ModalEditContact from "./parts/ModalEditContact";
import { FaEdit, FaTrash, FaEnvelope, FaPhone, FaPlus, FaSignOutAlt } from 'react-icons/fa';
import { useAuth } from "../../hooks/useAuth";

export default function Home() {
  const [popUpSignIn, setPopUpSignIn] = useState(false);
  const [openModalAddContact, setOpenModalAddContact] = useState(false);
  const [openModalDeleteContact, setOpenModalDeleteContact] = useState<
  {id: string, name: string, email: string, phone: string} | null>(null);
  const [openModalEditContact, setOpenModalEditContact] = useState<{id: string, name: string, email: string, phone: string} | null>(null);
  const { error } = useUser();
  const { logout } = useAuth();
  const {
    contacts,
    isLoading,
    error: contactError,
  } = useContacts();

  useEffect(() => {
    const token = localStorage.getItem('token');
    if (!token || error) {
      setPopUpSignIn(true);
    } else {
      setPopUpSignIn(false);
    }
  }, [error]);

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 font-sans relative overflow-hidden">
      {/* Background ambient glows */}
      <div className="fixed top-20 left-10 w-96 h-96 bg-cyan-500/5 rounded-full blur-[100px] pointer-events-none"></div>
      <div className="fixed bottom-20 right-10 w-96 h-96 bg-blue-500/5 rounded-full blur-[100px] pointer-events-none"></div>

      {/* Navigation */}
      <nav className="bg-slate-950/80 backdrop-blur-md border-b border-slate-900 fixed w-full top-0 z-40">
        <div className="container mx-auto px-6 py-3 flex justify-between items-center">
          <div className="flex items-center gap-3">
            <div className="flex items-center gap-1.5 relative group">
              <img 
                src="https://upload.wikimedia.org/wikipedia/commons/a/a7/React-icon.svg" 
                alt="React Logo" 
                className="w-7 h-7 animate-[spin_20s_linear_infinite]" 
              />
              <img 
                src="https://upload.wikimedia.org/wikipedia/commons/4/4c/Typescript_logo_2020.svg" 
                alt="TypeScript Logo" 
                className="w-6 h-6 rounded shadow-md shadow-blue-500/10" 
              />
              <div className="absolute -inset-2 bg-gradient-to-r from-[#61dafb]/15 to-[#3178c6]/15 rounded-lg blur opacity-0 group-hover:opacity-100 transition-opacity duration-500"></div>
            </div>
            <h1 className="text-xl font-extrabold tracking-wider bg-clip-text text-transparent bg-gradient-to-r from-white to-[#61dafb] select-none">
              R-Contacts
            </h1>
          </div>
          <button
            onClick={logout}
            className="inline-flex items-center gap-2 px-4 py-2 bg-rose-950/30 hover:bg-rose-950/50 border border-rose-900/40 hover:border-rose-800/60 text-rose-300 hover:text-rose-200 text-sm font-semibold rounded-xl transition-all duration-300 cursor-pointer"
          >
            <FaSignOutAlt className="w-3.5 h-3.5" />
            Logout
          </button>
        </div>
      </nav>

      <main className="container mx-auto px-6 pt-24 pb-12 relative z-10">
        <div className="flex justify-between items-center mb-8">
          <div className="space-y-1">
            <h2 className="text-2xl md:text-3xl font-extrabold text-white tracking-tight">Your Contacts</h2>
            <p className="text-xs text-slate-500 font-mono">
              {contacts ? `${contacts.length} record(s) loaded` : 'loading...'}
            </p>
          </div>
          <button
            onClick={() => setOpenModalAddContact(true)}
            className="inline-flex items-center gap-2 px-5 py-2.5 bg-gradient-to-r from-[#61dafb] to-[#3178c6] hover:from-[#21b4d6] hover:to-[#255ba1] text-white font-bold rounded-xl text-sm transition-all duration-300 shadow-md shadow-[#61dafb]/10 hover:shadow-[#61dafb]/20 transform hover:-translate-y-0.5 active:translate-y-0 cursor-pointer"
          >
            <FaPlus className="w-3 h-3" />
            Add Contact
          </button>
        </div>

        {/* Modals */}
        {popUpSignIn && <ModalSignIn />}
        {openModalAddContact && <ModalAddContact onClose={() => setOpenModalAddContact(false)} />}
        {openModalDeleteContact && <ModalDeleteContact
          id={openModalDeleteContact.id}
          name={openModalDeleteContact.name}
          email={openModalDeleteContact.email}
          phone={openModalDeleteContact.phone}
          onClose={() => setOpenModalDeleteContact(null)}
          />}
        {openModalEditContact && <ModalEditContact
          id={openModalEditContact.id}
          name={openModalEditContact.name}
          email={openModalEditContact.email}
          phone={openModalEditContact.phone}
          onClose={() => setOpenModalEditContact(null)}
          />}

        {/* Loading State */}
        {isLoading && (
          <div className="flex justify-center items-center py-20">
            <div className="text-sm font-mono text-[#61dafb] animate-pulse">[status]: fetching contact records...</div>
          </div>
        )}

        {/* Error State */}
        {contactError && (
          <div className="max-w-md mx-auto px-4 py-3 bg-red-950/20 border border-red-900/40 text-red-400 text-xs font-mono rounded-xl text-center">
            [error]: {contactError.message}
          </div>
        )}

        {/* Empty State */}
        {contacts && contacts.length === 0 && (
          <div className="flex flex-col items-center justify-center py-20 gap-4">
            <div className="w-16 h-16 rounded-2xl bg-slate-900 border border-slate-800 flex items-center justify-center">
              <FaPhone className="text-2xl text-slate-600" />
            </div>
            <p className="text-sm text-slate-500 font-mono">No contacts found. Add your first contact.</p>
          </div>
        )}

        {/* Contact Grid */}
        {contacts && contacts.length > 0 && (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
            {contacts.map((contact: {id: string, name: string, email: string, phone: string}) => (
              <div 
                key={contact.id} 
                className="bg-slate-900/50 backdrop-blur-sm border border-slate-800/80 hover:border-[#61dafb]/30 p-6 rounded-2xl shadow-md hover:shadow-[0_0_25px_rgba(97,218,251,0.06)] transition-all duration-300 transform hover:-translate-y-1 group"
              >
                <div className="flex items-start justify-between mb-4">
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-[#61dafb]/20 to-[#3178c6]/20 border border-slate-800 flex items-center justify-center text-[#61dafb] font-bold text-sm">
                      {contact.name.charAt(0).toUpperCase()}
                    </div>
                    <h3 className="text-base font-bold text-white group-hover:text-[#61dafb] transition-colors duration-300">{contact.name}</h3>
                  </div>
                </div>

                <div className="space-y-2 mb-5">
                  <p className="text-xs text-slate-400 flex items-center gap-2">
                    <FaEnvelope className="w-3 h-3 text-slate-600" />
                    {contact.email}
                  </p>
                  <p className="text-xs text-slate-400 flex items-center gap-2">
                    <FaPhone className="w-3 h-3 text-slate-600" />
                    {contact.phone}
                  </p>
                </div>

                <div className="flex gap-2 pt-3 border-t border-slate-800/60">
                  <button
                    onClick={() => setOpenModalEditContact(contact)}
                    className="flex-1 inline-flex items-center justify-center gap-1.5 py-2 px-3 bg-slate-850 hover:bg-[#3178c6]/20 border border-slate-800 hover:border-[#3178c6]/40 text-slate-300 hover:text-[#61dafb] text-xs font-semibold rounded-lg transition-all duration-300 cursor-pointer"
                  >
                    <FaEdit className="w-3 h-3" />
                    Edit
                  </button>
                  <button
                    onClick={() => setOpenModalDeleteContact(contact)}
                    className="flex-1 inline-flex items-center justify-center gap-1.5 py-2 px-3 bg-rose-950/15 hover:bg-rose-950/30 border border-rose-900/30 hover:border-rose-800/50 text-rose-400 hover:text-rose-300 text-xs font-semibold rounded-lg transition-all duration-300 cursor-pointer"
                  >
                    <FaTrash className="w-3 h-3" />
                    Delete
                  </button>
                </div>
              </div>
            ))}
          </div>
        )}
      </main>
    </div>
  )
}

// vue/src/modules/home/Home.vue
<script setup>
import { ref, watch } from 'vue';
import { useContact } from '../../hooks/useContact';
import ContactCard from '../../components/ContactCard.vue';
import { useAuth } from '../../hooks/useAuth';
import { useRouter } from 'vue-router';
import ModalDeleteContact from './parts/ModalDeleteContact.vue';
import ModalEditContact from './parts/ModalEditContact.vue';
import ModalAddContact from './parts/ModalAddContact.vue';
import VueLogo from '../../assets/vue.svg';
import { Icon } from '@iconify/vue';

// Menggunakan hook useContact untuk berinteraksi dengan data
const { 
    contacts, 
    isFetchingContacts, 
    fetchContactsError
} = useContact();

const { logout, error: authError } = useAuth();

const router = useRouter();

const searchTerm = ref('');
const filteredContacts = ref([]);

const modalAddOpen = ref(false);
const modalEditOpen = ref(false);
const modalDeleteOpen = ref(false);

const selectedContact = ref(null);

const closeModal = () => {
    modalAddOpen.value = false;
    modalEditOpen.value = false;
    modalDeleteOpen.value = false;
    selectedContact.value = null;
};

const handleAdd = () => {
    modalAddOpen.value = true;
}

const handleEdit = (contact) => {
    modalEditOpen.value = true;
    selectedContact.value = contact;
}

const handleDelete = (contact) => {
    modalDeleteOpen.value = true;
    selectedContact.value = contact
}

watch([contacts, searchTerm], () => {
  if (contacts.value) {
    filteredContacts.value = contacts.value.filter((contact) =>
      contact.name.toLowerCase().includes(searchTerm.value.toLowerCase())
    );
  }
}, { immediate: true });


watch(authError, (newError) => {
  if (newError) {
    localStorage.removeItem('token');
    router.push('/signin');
  }
});

watch(fetchContactsError, (newError) => {
  if (newError) {
    console.error("Contact service error:", newError);
  }
});

</script>

<template>
    <div class="min-h-screen bg-slate-950 text-slate-100 font-sans relative overflow-hidden pb-16">
        <!-- Cyber Background Grid -->
        <div class="absolute inset-0 bg-[linear-gradient(to_right,#0f172a_1px,transparent_1px),linear-gradient(to_bottom,#0f172a_1px,transparent_1px)] bg-[size:4rem_4rem] [mask-image:radial-gradient(ellipse_60%_50%_at_50%_50%,#000_70%,transparent_100%)] pointer-events-none"></div>
        <div class="absolute top-0 left-1/2 -translate-x-1/2 w-[600px] h-[300px] bg-[#42b883]/5 blur-[120px] rounded-full pointer-events-none"></div>

        <!-- Navigation Bar -->
        <nav class="sticky top-0 z-40 bg-slate-950/80 backdrop-blur-md border-b border-slate-900">
            <div class="container mx-auto px-6 py-4 flex justify-between items-center">
                <div class="flex items-center gap-3">
                    <div class="relative group">
                        <div class="absolute inset-0 bg-[#42b883]/30 blur-md rounded-full group-hover:bg-[#42b883]/50 transition-colors"></div>
                        <img :src="VueLogo" alt="Vue Logo" class="w-8 h-8 relative z-10 filter drop-shadow-[0_0_4px_rgba(66,184,131,0.3)]" />
                    </div>
                    <div>
                        <h1 class="text-lg font-bold font-mono tracking-widest text-white flex items-center gap-1.5">
                            RCONTACTS
                        </h1>
                        <span class="block text-[8px] font-mono text-slate-500 uppercase tracking-wider -mt-1">// USER_WORKSPACE</span>
                    </div>
                </div>
                <button
                    @click="logout"
                    class="relative px-4 py-2 border border-red-500/30 text-red-400 font-mono text-xs uppercase rounded-lg hover:bg-red-500/10 hover:border-red-500 hover:shadow-[0_0_15px_rgba(239,68,68,0.25)] transition-all duration-300 cursor-pointer flex items-center gap-2 group"
                >
                    <Icon icon="lucide:log-out" class="text-sm group-hover:translate-x-0.5 transition-transform" />
                    <span>TERMINATE_SESSION</span>
                </button>
            </div>
        </nav>

        <!-- Welcome Banner -->
        <div class="relative bg-slate-900/40 border-b border-slate-900/60 py-10 overflow-hidden">
            <div class="absolute inset-0 bg-[radial-gradient(ellipse_at_center,rgba(66,184,131,0.03),transparent_70%)] pointer-events-none"></div>
            <div class="container mx-auto px-6 text-center relative z-10">
                <div class="relative inline-block mb-4">
                    <div class="absolute inset-0 bg-[#42b883]/10 blur-xl rounded-full"></div>
                    <img
                        :src="VueLogo"
                        alt="Vue Logo"
                        class="w-20 h-20 mx-auto filter drop-shadow-[0_0_15px_rgba(66,184,131,0.25)] animate-[spin_20s_linear_infinite]"
                    />
                </div>
                <h2 class="text-3xl font-extrabold font-mono text-white tracking-wider uppercase mb-1">
                    WELCOME_TO_RCONTACTS
                </h2>
                <p class="text-slate-400 text-sm max-w-md mx-auto font-mono text-xs uppercase tracking-wider text-slate-500">
                    // CENTRALIZED_DIRECTORY_DECRYPTED
                </p>
            </div>
        </div>

        <!-- Dashboard Content -->
        <div class="container mx-auto px-6 mt-8 relative z-10">
            <!-- Search & Actions -->
            <div class="flex flex-col md:flex-row justify-between items-stretch md:items-center gap-4 mb-8">
                <!-- Search Bar -->
                <div class="relative flex-1 max-w-md group">
                    <span class="absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-500 group-focus-within:text-[#42b883] transition-colors">
                        <Icon icon="lucide:search" class="text-lg" />
                    </span>
                    <input
                        type="text"
                        placeholder="SEARCH_DIRECTORY..."
                        class="w-full pl-10 pr-4 py-2.5 bg-slate-900/80 border border-slate-800 rounded-lg text-slate-100 font-mono text-sm placeholder-slate-700 focus:outline-none focus:border-[#42b883] focus:shadow-[0_0_15px_rgba(66,184,131,0.15)] transition-all duration-300"
                        v-model="searchTerm"
                    />
                </div>

                <!-- Add Button -->
                <button
                    @click="handleAdd"
                    class="relative group overflow-hidden bg-gradient-to-r from-[#42b883] to-[#35495e] text-slate-950 font-bold font-mono text-xs uppercase px-5 py-2.5 rounded-lg hover:shadow-[0_0_20px_rgba(66,184,131,0.35)] transition-all duration-300 flex items-center justify-center gap-2 cursor-pointer"
                >
                    <span class="absolute inset-0 bg-white/20 -translate-x-full group-hover:translate-x-full transition-transform duration-1000 ease-out"></span>
                    <Icon icon="lucide:user-plus" class="text-sm" />
                    <span>ADD_NEW_RECORD</span>
                </button>
            </div>

            <!-- Loader / Errors -->
            <div v-if="isFetchingContacts" class="py-20 text-center flex flex-col items-center justify-center gap-3">
                <Icon icon="line-md:loading-twotone-loop" class="text-[#42b883] text-4xl" />
                <p class="font-mono text-xs uppercase text-slate-500 tracking-widest animate-pulse">
                    fetching_directory_records...
                </p>
            </div>

            <div 
                v-else-if="fetchContactsError" 
                class="max-w-md mx-auto p-4 bg-red-950/30 border border-red-500/30 rounded-lg text-center"
            >
                <Icon icon="lucide:alert-triangle" class="text-red-500 text-3xl mx-auto mb-2" />
                <h3 class="font-mono font-bold text-sm uppercase text-red-400 mb-1">DATA_STREAM_ERROR</h3>
                <p class="font-mono text-xs text-red-500">{{ fetchContactsError.message || fetchContactsError }}</p>
            </div>

            <!-- Contacts Cards Grid -->
            <div v-else-if="filteredContacts && filteredContacts.length > 0" class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                <ContactCard 
                    v-for="contact in filteredContacts" 
                    :key="contact.id" 
                    :contact="contact"
                    @edit="() => handleEdit(contact)"
                    @delete="() => handleDelete(contact)"
                />
            </div>

            <!-- Empty State -->
            <div 
                v-else 
                class="py-20 border border-dashed border-slate-900 rounded-xl bg-slate-900/10 text-center max-w-lg mx-auto"
            >
                <Icon icon="lucide:folder-open" class="text-slate-700 text-4xl mx-auto mb-3" />
                <h3 class="font-mono font-bold text-sm text-slate-400 uppercase mb-1">NO_RECORDS_FOUND</h3>
                <p class="font-mono text-xs text-slate-600">The requested query does not exist in local directory nodes.</p>
            </div>

            <!-- Modals Edit -->
             <ModalEditContact 
                v-if="modalEditOpen"
                :contact="selectedContact"
                @close="closeModal"
             />

            <!-- Modals Delete -->
             <ModalDeleteContact 
                v-if="modalDeleteOpen"
                :contact="selectedContact"
                @close="closeModal"
             />

            <!-- Modal Add -->
            <ModalAddContact
                v-if="modalAddOpen"
                @close="closeModal"
            />
        </div>
    </div>
</template>
