// vue/src/modules/home/parts/ModalEditContact.vue
<script setup>
import { defineEmits, ref, defineProps } from 'vue';
import { useContact } from '../../../hooks/useContact';
import { watch } from 'vue';
import { Icon } from '@iconify/vue';

const props = defineProps({
  contact: {
    type: Object,
    required: true
  }
})

const formData = ref({
  name: props.contact.name || "",
  email: props.contact.email || "",
  phone: props.contact.phone || "",
})

const { updateContactMutate, isUpdatingContact, updateContactError } = useContact();

const emit = defineEmits(['close']);

function handleSave() {
  updateContactMutate({
    contactId: props.contact.id,
    name: formData.value.name,
    email: formData.value.email,
    phone: formData.value.phone,
  }, {
    onSuccess: () => {
      closeModal();
    }
  })
}

watch(updateContactError, (newError) => {
  if (newError) {
    console.error("Contact service error:", newError);
  }
});

function closeModal() {
  emit('close');
}
</script>

<template>
  <div class="fixed inset-0 bg-slate-950/70 backdrop-blur-sm flex items-center justify-center z-50 p-4" @click.self="closeModal">
    <div class="relative bg-slate-900/95 border border-slate-800 rounded-xl p-6 w-full max-w-md shadow-[0_0_30px_rgba(0,0,0,0.6)] overflow-hidden">
      <!-- Top Tech Bar accent -->
      <div class="absolute top-0 left-0 right-0 h-[2px] bg-gradient-to-r from-transparent via-[#42b883] to-transparent"></div>
      
      <!-- Tech Decors -->
      <div class="absolute top-2 right-4 font-mono text-[8px] text-slate-700 select-none">NODE_EDIT_PORT</div>

      <!-- Header -->
      <h2 class="text-xl font-bold font-mono tracking-wider text-white uppercase mb-6 flex items-center gap-2">
        <span class="w-1.5 h-1.5 bg-[#42b883] rounded-full shadow-[0_0_6px_#42b883]"></span>
        EDIT_RECORD
      </h2>

      <!-- Form -->
      <form @submit.prevent="handleSave" class="space-y-4">
        <!-- Name Input -->
        <div>
          <label class="block text-xs font-bold font-mono uppercase text-slate-400 mb-1.5 tracking-wider flex justify-between">
            <span>FULL_NAME</span>
            <span class="text-slate-600">*REQUIRED</span>
          </label>
          <div class="relative group">
            <span class="absolute left-3.5 top-1/2 -translate-y-1/2 text-xs font-mono text-slate-500 group-focus-within:text-[#42b883] transition-colors">ID</span>
            <input 
              type="text" 
              required
              class="w-full pl-9 pr-4 py-2.5 bg-slate-950/80 border border-slate-800 rounded-lg text-slate-100 font-mono text-sm placeholder-slate-700 focus:outline-none focus:border-[#42b883] focus:shadow-[0_0_15px_rgba(66,184,131,0.15)] transition-all duration-300"
              placeholder="Enter record name" 
              v-model="formData.name"
            />
          </div>
        </div>

        <!-- Email Input -->
        <div>
          <label class="block text-xs font-bold font-mono uppercase text-slate-400 mb-1.5 tracking-wider flex justify-between">
            <span>EMAIL_ADDRESS</span>
            <span class="text-slate-600">//OPTIONAL</span>
          </label>
          <div class="relative group">
            <span class="absolute left-3.5 top-1/2 -translate-y-1/2 text-xs font-mono text-slate-500 group-focus-within:text-[#42b883] transition-colors">@</span>
            <input 
              type="email" 
              class="w-full pl-9 pr-4 py-2.5 bg-slate-950/80 border border-slate-800 rounded-lg text-slate-100 font-mono text-sm placeholder-slate-700 focus:outline-none focus:border-[#42b883] focus:shadow-[0_0_15px_rgba(66,184,131,0.15)] transition-all duration-300"
              placeholder="Enter record email" 
              v-model="formData.email"
            />
          </div>
        </div>

        <!-- Phone Input -->
        <div>
          <label class="block text-xs font-bold font-mono uppercase text-slate-400 mb-1.5 tracking-wider flex justify-between">
            <span>PHONE_NUMBER</span>
            <span class="text-slate-600">*REQUIRED</span>
          </label>
          <div class="relative group">
            <span class="absolute left-3.5 top-1/2 -translate-y-1/2 text-xs font-mono text-slate-500 group-focus-within:text-[#42b883] transition-colors">PH</span>
            <input 
              type="text" 
              required
              class="w-full pl-9 pr-4 py-2.5 bg-slate-950/80 border border-slate-800 rounded-lg text-slate-100 font-mono text-sm placeholder-slate-700 focus:outline-none focus:border-[#42b883] focus:shadow-[0_0_15px_rgba(66,184,131,0.15)] transition-all duration-300"
              placeholder="Enter record phone" 
              v-model="formData.phone"
            />
          </div>
        </div>

        <!-- Action Buttons -->
        <div class="flex justify-end gap-3 pt-4 border-t border-slate-900 mt-6">
          <button 
            type="button" 
            @click="closeModal" 
            class="px-4 py-2 border border-slate-800 text-slate-400 font-mono text-xs uppercase rounded-lg hover:bg-slate-800 hover:text-white transition-all duration-200 cursor-pointer"
          >
            CANCEL
          </button>
          
          <button 
            type="submit" 
            class="relative group overflow-hidden bg-gradient-to-r from-[#42b883] to-[#35495e] text-slate-950 font-bold font-mono text-xs uppercase px-5 py-2 rounded-lg hover:shadow-[0_0_15px_rgba(66,184,131,0.3)] transition-all duration-300 flex items-center justify-center gap-1.5 cursor-pointer"
            :disabled="isUpdatingContact"
          >
            <Icon v-if="isUpdatingContact" icon="line-md:loading-twotone-loop" class="text-slate-950 text-xs" />
            <span>{{ isUpdatingContact ? 'SAVING...' : 'SAVE_CHANGES' }}</span>
          </button>
        </div>
      </form>

      <!-- Error Message -->
      <div 
        v-if="updateContactError" 
        class="mt-4 p-3 bg-red-950/30 border border-red-500/30 rounded-lg text-xs font-mono text-red-400 flex gap-2 items-start"
      >
        <Icon icon="lucide:alert-triangle" class="text-red-500 mt-0.5 shrink-0" />
        <div>
          <div class="font-bold uppercase">SAVE_FAILED</div>
          <div>{{ updateContactError.message || updateContactError }}</div>
        </div>
      </div>
    </div>
  </div>
</template>

// react-ts/src/modules/home/parts/ModalEditContact.tsx
import { useContacts } from "../../../hooks/useContact"
import { useState } from "react";
import { FaTimes } from 'react-icons/fa';

type ModalEditContactProps = {
  id: string;
  name: string;
  email: string;
  phone: string;
  onClose: () => void;
}

export default function ModalEditContact({id, name, email, phone, onClose}: ModalEditContactProps) {

  const {editContact, isEditing, editError} = useContacts();
  const [editData, setEditData] = useState({
    name,
    email,
    phone,
  });

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setEditData({
      ...editData,
      [e.target.name]: e.target.value,
    });
  }

  const handleSubmit = () => {
    if (editData.name.trim() === "" || editData.email.trim() === "" || editData.phone.trim() === "") {
      return;
    }
    editContact({id, name: editData.name, email: editData.email, phone: editData.phone});
    if(!editError){
      onClose();
    }
  }

  return (
    <div className="fixed inset-0 bg-transparent backdrop-blur flex justify-center items-center z-50">
      <div className="bg-white border-2 border-[#61dafb] rounded-lg shadow-lg w-96 p-6 relative">
        <button onClick={onClose} className="absolute top-2 right-2 text-gray-500 hover:text-gray-700">
          <FaTimes />
        </button>
        <div className="flex justify-center items-center mb-4">
          <img src="https://upload.wikimedia.org/wikipedia/commons/a/a7/React-icon.svg" alt="React Logo" className="w-8 h-8 mr-2" />
          <img src="https://upload.wikimedia.org/wikipedia/commons/4/4c/Typescript_logo_2020.svg" alt="TypeScript Logo" className="w-8 h-8" />
        </div>
        <h2 className="text-2xl font-bold mb-6 text-center text-[#3178c6]">Edit Contact</h2>

        {/* Name */}
        <div className="mb-4">
          <label htmlFor="name" className="block text-[#3178c6] mb-2">Name</label>
          <input
            type="text"
            id="name"
            name="name"
            className="w-full px-3 py-2 border border-gray-300 rounded-lg text-[#3178c6]
                   focus:outline-none focus:ring-2 focus:ring-[#61dafb]"
            placeholder="Enter name"
            value={editData.name}
            onChange={handleChange}
          />
        </div>

        {/* Email */}
        <div className="mb-4">
          <label htmlFor="email" className="block text-[#3178c6] mb-2">Email</label>
          <input
            type="email"
            id="email"
            name="email"
            className="w-full px-3 py-2 border border-gray-300 rounded-lg text-[#3178c6]
                   focus:outline-none focus:ring-2 focus:ring-[#61dafb]"
            placeholder="Enter email"
            value={editData.email}
            onChange={handleChange}
          />
        </div>

        {/* Phone */}
        <div className="mb-6">
          <label htmlFor="phone" className="block text-[#3178c6] mb-2">Phone</label>
          <input
            type="text"
            id="phone"
            name="phone"
            className="w-full px-3 py-2 border border-gray-300 rounded-lg text-[#3178c6]
                   focus:outline-none focus:ring-2 focus:ring-[#61dafb]"
            placeholder="Enter phone"
            value={editData.phone}
            onChange={handleChange}
          />
        </div>

        {/* Buttons */}
        <div className="flex space-x-2">
          <button
            onClick={handleSubmit}
            className="flex-1 bg-[#61dafb] text-white py-2 rounded-lg hover:bg-[#21b4d6] transition-colors shadow-md"
            disabled={isEditing}
          >
            {isEditing ? 'Saving...' : 'Save Changes'}
          </button>
          <button
            onClick={onClose}
            className="flex-1 bg-gray-500 text-white py-2 rounded-lg hover:bg-gray-600 transition-colors shadow-md"
          >
            Cancel
          </button>
        </div>
        {editError && <p className="mt-4 text-center text-red-500">{editError.message}</p>}
      </div>
    </div>
  )
}
